from enum import Enum


class EcgSamplingRate(Enum):
    ECG_SAMPLE_RATE_64HZ = 0
    ECG_SAMPLE_RATE_128HZ = 1
    ECG_SAMPLE_RATE_256HZ = 2


class EcgPgaGain(Enum):
    PGA_GAIN_1 = 0
    PGA_GAIN_2 = 1
    PGA_GAIN_4 = 2
    PGA_GAIN_8 = 3
    PGA_GAIN_16 = 7


class EcgInaGain(Enum):
    INA_GAIN_0 = 0
    INA_GAIN_1 = 1
    INA_GAIN_2 = 2
    INA_GAIN_3 = 3


class EcgInaRange(Enum):
    ECG_INA_GAIN_RGE_0 = 0
    ECG_INA_GAIN_RGE_1 = 1
    ECG_INA_GAIN_RGE_2 = 2
    ECG_INA_GAIN_RGE_3 = 3


class EcgInputPolarity(Enum):
    ECG_INPUT_NON_INVERTED = 0
    ECG_INPUT_INVERTED = 1


class EcgLeadOffMode(Enum):
    ECG_LEAD_OFF_DC = 0
    ECG_LEAD_OFF_AC = 1


class EcgLeadOffCurrentPolarity(Enum):
    ECG_LEAD_OFF_NON_INVERTED = 0
    ECG_LEAD_OFF_INVERTED = 1


class EcgLeadOffCurrentMagnitude(Enum):
    ECG_LEAD_OFF_IMAG_0 = 0
    ECG_LEAD_OFF_IMAG_5 = 1
    ECG_LEAD_OFF_IMAG_10 = 2
    ECG_LEAD_OFF_IMAG_20 = 3
    ECG_LEAD_OFF_IMAG_50 = 4
    ECG_LEAD_OFF_IMAG_100 = 5
    ECG_LEAD_OFF_IMAG_200 = 6
    ECG_LEAD_OFF_IMAG_400 = 7


class EcgLeadOffVoltageThreshold(Enum):
    ECG_LEAD_OFF_VOL_THRESH_25MV = 0
    ECG_LEAD_OFF_VOL_THRESH_50MV = 1
    ECG_LEAD_OFF_VOL_THRESH_75MV = 2
    ECG_LEAD_OFF_VOL_THRESH_100MV = 3
    ECG_LEAD_OFF_VOL_THRESH_125MV = 4
    ECG_LEAD_OFF_VOL_THRESH_150MV = 5
    ECG_LEAD_OFF_VOL_THRESH_175MV = 6
    ECG_LEAD_OFF_VOL_THRESH_200MV = 7
    ECG_LEAD_OFF_VOL_THRESH_225MV = 8
    ECG_LEAD_OFF_VOL_THRESH_250MV = 9
    ECG_LEAD_OFF_VOL_THRESH_275MV = 10
    ECG_LEAD_OFF_VOL_THRESH_300MV = 11
    ECG_LEAD_OFF_VOL_THRESH_325MV = 12
    ECG_LEAD_OFF_VOL_THRESH_350MV = 13
    ECG_LEAD_OFF_VOL_THRESH_375MV = 14
    ECG_LEAD_OFF_VOL_THRESH_400MV = 15


class EcgLeadOffFreq(Enum):
    ECG_LEAD_OFF_FREQ_DISABLE = 0
    ECG_LEAD_OFF_FREQ_8192HZ = 1
    ECG_LEAD_OFF_FREQ_4096HZ = 2
    ECG_LEAD_OFF_FREQ_2048HZ = 3
    ECG_LEAD_OFF_FREQ_1024HZ = 4
    ECG_LEAD_OFF_FREQ_512HZ = 5
    ECG_LEAD_OFF_FREQ_256HZ = 6
    ECG_LEAD_OFF_FREQ_128HZ = 7


class PpgSamplingRate(Enum):
    ECG_SAMPLE_RATE_64HZ = 0
    ECG_SAMPLE_RATE_128HZ = 1
    ECG_SAMPLE_RATE_256HZ = 2


class AccelSamplingRate(Enum):
    ACC_SAMPLE_RATE_12Hz5 = 1
    ACC_SAMPLE_RATE_26Hz = 2
    ACC_SAMPLE_RATE_52Hz = 3
    ACC_SAMPLE_RATE_104Hz = 4
    ACC_SAMPLE_RATE_208Hz = 5


class AccelFullScaleRange(Enum):
    ACC_FS_2G = 0
    ACC_FS_16G = 1
    ACC_FS_4G = 2
    ACC_FS_8G = 3
